ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE site_feedback ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'open';
